# Exported from Render on 2026-09-27T16:16:51Z
version: "1"
services:
- type: web
  name: mmusda-backend
  runtime: node
  repo: https://github.com/Joshua-A-tech/mmusdaweb
  plan: free
  envVars:
  - key: CLOUD_API_SECRET
    sync: false
  - key: YOUTUBE_API_KEY
    sync: false
  - key: EMAIL_PASS
    sync: false
  - key: Database_URL
    sync: false
  - key: CLOUD_API_KEY
    sync: false
  - key: CLOUD_NAME
    sync: false
  - key: YOUTUBE_CHANNEL_ID
    sync: false
  - key: EMAIL_USER
    sync: false
  - key: JWT_SECRET
    sync: false
  - key: NODE_VERSION
    sync: false
  region: ohio
  buildCommand: corepack enable && pnpm install
  startCommand: pnpm start
  healthCheckPath: /sermons/initial
  autoDeployTrigger: commit
  rootDir: backend
- type: web
  name: mmusda-admin
  runtime: static
  repo: https://github.com/Joshua-A-tech/mmusdaweb
  envVars:
  - key: VITE_API_URL
    sync: false
  buildCommand: corepack enable && pnpm install && pnpm run build
  staticPublishPath: ./dist
  routes:
  - type: rewrite
    source: /*
    destination: /index.html
  autoDeployTrigger: commit
  rootDir: admin
- type: web
  name: mmusda-web
  runtime: static
  repo: https://github.com/Joshua-A-tech/mmusdaweb
  envVars:
  - key: VITE_API_URL
    sync: false
  buildCommand: corepack enable && pnpm install && pnpm run build
  staticPublishPath: ./dist
  routes:
  - type: rewrite
    source: /*
    destination: /index.html
  autoDeployTrigger: commit
  rootDir: frontend
